### ISSUE TITLE
models/__init__.py 中的代码似乎是冗余的

### ISSUE THREAD

**Issue by zza234s** [zhenqincn/FedAPEN#1]
作者您好，感谢您愿意开源代码并且提供详细的运行示例，恭喜中稿KDD~

在运行您的代码时碰到了两个小小的问题：

1. models/__init__.py 里的代码似乎是冗余的，不删除的话会报无法导入对应模块的错误 

https://github.com/zhenqincn/FedAPEN/blob/e84119d0faf265441b1fbdc44e69f4a7f1e75cf9/models/__init__.py#L1-L9

2. main函数第56行导致报错：TypeError: __init__() got an unexpected keyword argument 'choice'
这里我将关键字choice改为choices后问题解决（我不确定是不是我的环境版本问题所导致）
https://github.com/zhenqincn/FedAPEN/blob/e84119d0faf265441b1fbdc44e69f4a7f1e75cf9/main.py#L56

在解决上面两个小问题后，在我的主机上就能顺利运行仓库的代码了

**Comment by zhenqincn** [comment]
非常感谢您能指出这两个问题。这个代码是我们将实验用的代码整理了一下发布的，整理后测试不充分直接发布了。
这两个问题的原因分别如下：
1. 我们整理代码的时候删除了一些不必要的模型，但是清理不够彻底；
2. 为了方便读者理解--iid参数的设置，我们给出了一些样例，错误地少打了一个s。

您的修改方式非常正确，我们也已按照您的建议更新了代码。
